### ISSUE TITLE
Where can I get the refresh token?

### ISSUE THREAD

**Issue by franciscocpg** [vially/gauthtoken#1]
What are the steps to get the refresh token?

**Comment by vially** [comment]
After you have authenticated using the Google Cloud SDK you can get it from: `~/.config/gcloud/credentials`.

**Comment by franciscocpg** [comment]
Thank you @vially.
What do you think about putting this information at README.md?

**Comment by vially** [comment]
Sure, I hope I'll manage to do that soon.
